version: "3.0"
services:
  databus:
    image: "dbpedia/databus"
    ports:
      - 3000:3000
      - 3001:8080 
    environment:
      DATABUS_RESOURCE_BASE_URL: ${DATABUS_RESOURCE_BASE_URL}
      DATABUS_DATABASE_URL: "http://gstore:80"
      DATABUS_OIDC_ISSUER_BASE_URL: ${DATABUS_OIDC_ISSUER_BASE_URL}
      DATABUS_OIDC_CLIENT_ID: ${DATABUS_OIDC_CLIENT_ID}
      DATABUS_OIDC_SECRET: ${DATABUS_OIDC_SECRET}
      DATABUS_DEFAULT_CONTEXT_URL: https://downloads.dbpedia.org/databus/context.jsonld
    volumes:
      - ./data/keypair/:/databus/server/keypair
      - ./data/users/:/databus/server/users
  gstore:
    image: "dbpedia/gstore"
    environment:
      VIRT_USER: ${VIRTUOSO_USER}
      VIRT_PASS: ${VIRTUOSO_PASSWORD}
      VIRT_URI: "http://virtuoso:8890"
      GIT_ROOT: "/root/git"
    ports:
      - "3002:8080"
    volumes:
      - ./data/repo:/root/git
  virtuoso:
    image: "tenforce/virtuoso"
    environment:
      DBA_PASSWORD: ${VIRTUOSO_PASSWORD}
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: ${DATABUS_RESOURCE_BASE_URL}
    ports:
      - "3003:8890"
    volumes:
      - ./data/virtuoso:/database