version: "3.0"
services:
  download:
    image: dbpedia/dbpedia-databus-collection-downloader:latest
    environment:
      COLLECTION_URI: https://databus.dbpedia.org/jan/collections/more-cities/
      TARGET_DIR: /root/data
    volumes:
      - ./data:/root/data
  dbpedia-lookup-search:
    image: dbpedia/dbpedia-lookup:latest
    ports:
      - 9273:8080
    environment:
      - CONFIG_PATH=/root/app-config.yml
    volumes: 
      - ./app-config.yml:/root/app-config.yml
      - ./template.xsl:/root/template.xsl
      - ./index:/root/index/
      - ./data:/root/data/
      - ./tdb:/root/tdb
