version: "3.0"
services:
  databus:
    image: "dbpedia/databus"
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:3001:8080
    environment:
      DATABUS_RESOURCE_BASE_URL: ${DATABUS_RESOURCE_BASE_URL}
      DATABUS_DATABASE_URL: "http://gstore:8080"
      DATABUS_OIDC_ISSUER_BASE_URL: ${DATABUS_OIDC_ISSUER_BASE_URL}
      DATABUS_NAME: ${DATABUS_NAME}
      DATABUS_OIDC_CLIENT_ID: ${DATABUS_OIDC_CLIENT_ID}
      DATABUS_OIDC_SECRET: ${DATABUS_OIDC_SECRET}
      DATABUS_DEFAULT_CONTEXT_URL: https://downloads.dbpedia.org/databus/context.jsonld
    volumes:
      - ./data/keypair/:/databus/server/keypair
      - ./data/users/:/databus/server/users
  gstore:
    image: "dbpedia/gstore"
    environment:
      VIRT_USER: ${VIRTUOSO_USER}
      VIRT_PASS: ${VIRTUOSO_PASSWORD}
      VIRT_URI: "http://virtuoso:8890"
      GIT_ROOT: "/root/git"
    ports:
      - "127.0.0.1:3002:8080"
    volumes:
      - ./data/repo:/root/git
  virtuoso:
    image: "openlink/virtuoso-opensource-7"
    environment:
      DBA_PASSWORD: ${VIRTUOSO_PASSWORD}
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: ${DATABUS_RESOURCE_BASE_URL}
    ports:
      - "127.0.0.01:3003:8890"
    volumes:
      - ./data/virtuoso:/database
    entrypoint: /bin/bash -c "
        echo 'grant SPARQL_LOAD_SERVICE_DATA to \"SPARQL\";' > /opt/virtuoso-opensource/initdb.d/ini.sql &&
        echo 'grant SPARQL_SPONGE to \"SPARQL\";' >> /opt/virtuoso-opensource/initdb.d/ini.sql &&
        /virtuoso-entrypoint.sh
      "
